server.port: 8080
spring:
  application:
    name: ethereum-scanner
  main:
    allow-bean-definition-overriding: false
  r2dbc:
    url: r2dbc:postgresql://${DB_IP_PORT:localhost}/opex_scanner
    username: ${dbusername:opex}
    password: ${dbpassword:hiopex}
    initialization-mode: always
  cloud:
    bootstrap:
      enabled: true
    consul:
      host: ${CONSUL_HOST}
      port: 8500
      discovery:
        #healthCheckPath: ${management.context-path}/health
        instance-id: ${spring.application.name}:${server.port}
        healthCheckInterval: 20s
        prefer-ip-address: true
logging:
  level:
    co.nilin: DEBUG
    reactor.netty.http.client: DEBUG
swagger.authUrl: https://api.opex.dev
app:
  chain-name: ${CHAIN_NAME}