version: '3.8'
services:
  scanner-scheduler:
    image: ghcr.io/opexdev/scanner-scheduler
    build: scheduler-app
  ethereum-scanner:
    image: ghcr.io/opexdev/ethereum-scanner
    build: ethereum-app
  bitcoin-scanner:
    image: ghcr.io/opexdev/bitcoin-scanner
    build: bitcoin-app
  bsc-scanner:
    image: ghcr.io/opexdev/bsc-scanner
    build: ethereum-app
  tron-scanner:
    image: ghcr.io/opexdev/tron-scanner
    build: tron-app
