version: '3.8'
services:
  scanner-scheduler:
    image: ghcr.io/opexdev/scanner-scheduler:$TAG
    build: scheduler/scheduler-app
  ethereum-scanner:
    image: ghcr.io/opexdev/ethereum-scanner:$TAG
    build: ethereum-scanner-app
  bitcoin-scanner:
    image: ghcr.io/opexdev/bitcoin-scanner:$TAG
    build: bitcoin-scanner-app
  tron-scanner:
    image: ghcr.io/opexdev/tron-scanner:$TAG
    build: tron-scanner-app
