version: '3.8'
services:
  scanner-scheduler:
    image: ghcr.io/opexdev/scanner-scheduler
    build: scheduler
  eth-scanner:
    image: ghcr.io/opexdev/ethereum-scanner
    build: app-ethereum
  bitcoin-scanner:
    image: ghcr.io/opexdev/bitcoin-scanner
    build: bitcoin-scan
  bsc-scanner:
    image: ghcr.io/opexdev/bsc-scanner
    build: app-ethereum
  tron-scanner:
    image: ghcr.io/opexdev/tron-scanner
    build: app-tron
