version: '3.8'
services:
  gateway:
    image: ghcr.io/opexdev/gateway:$TAG
    build: gateway
  eth-scan:
    image: ghcr.io/opexdev/eth-scan:$TAG
    build: eth-scan
  bitcoin-scan:
    image: ghcr.io/opexdev/bitcoin-scan:$TAG
    build: bitcoin-scan
  tron-scan:
    image: ghcr.io/opexdev/tron-scan:$TAG
    build: tron-scan
