version: '3.8'
services:
  scanner-scheduler:
    image: ghcr.io/opexdev/scanner-scheduler:$TAG
    build: scheduler
  eth-scanner:
    image: ghcr.io/opexdev/ethereum-scanner:$TAG
    build: app-ethereum
  bitcoin-scanner:
    image: ghcr.io/opexdev/bitcoin-scanner:$TAG
    build: app-bitcoin
  tron-scanner:
    image: ghcr.io/opexdev/tron-scanner:$TAG
    build: app-tron
