server.port: 9992
spring:
  application:
    name: bitcoin-scan
  codec:
    max-in-memory-size: 10MB
  main:
    allow-bean-definition-overriding: false
  cloud:
    bootstrap:
      enabled: true
    consul:
      port: 8500
      discovery:
        #healthCheckPath: ${management.context-path}/health
        instance-id: ${spring.application.name}:${server.port}
        healthCheckInterval: 20s
        prefer-ip-address: true
logging:
  level:
    co.nilin: DEBUG
    reactor.netty.http.client: DEBUG
app:
  blockchain:
    rpc-url: $RPC_URL
    rest-url: $REST_URL
    api-key: $API_KEY