server.port: 8090

spring:
  application:
    name: chain-scan
  main:
    allow-bean-definition-overriding: false
  cloud:
    bootstrap:
      enabled: true
    consul:
      port: 8500
      discovery:
        #healthCheckPath: ${management.context-path}/health
        instance-id: ${spring.application.name}:${server.port}
        healthCheckInterval: 20s
        prefer-ip-address: true

swagger.authUrl: https://api.opex.dev
