spring:
  application:
    name: eth-scan
  main:
    allow-bean-definition-overriding: false
  cloud:
    consul:
      host: ${CONSUL_HOST}
      port: 8500

blockchain:
  url: https://eth.getblock.io/mainnet/?api_key=ba9c5c13-9efa-4a39-8c00-c6aed570944f

swagger.authUrl: https://api.opex.dev
