spring:
  application:
    name: scan-eth
  main:
    allow-bean-definition-overriding: false
  cloud:
    consul:
      host: ${CONSUL_HOST}
      port: 8500

blockchain:
  url: https://sample.mainnet

swagger.authUrl: https://api.opex.dev
