server.port: 9993
spring:
  application:
    name: tron-scan
  codec:
    max-in-memory-size: 10MB
  main:
    allow-bean-definition-overriding: false
  cloud:
    bootstrap:
      enabled: true
    consul:
      host: ${CONSUL_HOST}
      port: 8500
      discovery:
        #healthCheckPath: ${management.context-path}/health
        instance-id: ${spring.application.name}:${server.port}
        healthCheckInterval: 20s
        prefer-ip-address: true
logging:
  level:
    co.nilin: DEBUG
    reactor.netty.http.client: DEBUG
app:
  blockchain:
    rest-url: ${REST_ENDPOINT}
    api-key: ${API_KEY}