server.port: 8080
spring:
  main:
    allow-bean-definition-overriding: false
  r2dbc:
    url: r2dbc:postgresql://${DB_IP_PORT:localhost}/opex_scanner
    username: ${dbusername:opex}
    password: ${dbpassword:hiopex}
    initialization-mode: always
logging:
  level:
    co.nilin: TRACE
    reactor.netty.http.client: OFF
app:
  on-sync-webhook-url: http://bc-gateway
