spring:
  application:
    name: scanner-gateway
  main:
    allow-bean-definition-overriding: false
  r2dbc:
    url: r2dbc:postgresql://${DB_IP_PORT}/scanner-gateway
    username: opex
    password: hiopex
  cloud:
    consul:
      host: ${CONSUL_HOST}
      port: 8500