name: Push images on dev branch update

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        java: [ 11 ]
    name: Build OPEX and run tests with java ${{ matrix.java }}
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-package: jdk
          java-version: ${{ matrix.java }}
          cache: maven
      - name: Build
        run: mvn -B -T 1C clean install
      - name: Build Docker images
        run: TAG=dev docker-compose build --parallel
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push images to GitHub Container Registry
        run: TAG=dev docker-compose push
