name: Deploy Chain-Scan - Dev
on:
  push:
    branches:
      - dev
jobs:
  jenkinsJob:
    name: Deploy Chain-Scan
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Chain-Scan build job
        uses: appleboy/jenkins-action@master
        with:
          url: ${{ secrets.JENKINS_URL }}
          user: ${{ secrets.JENKINS_USER }}
          token: ${{ secrets.JENKINS_TOKEN }}
          job: "opex-chain-scan-dev"
